[package]
name = "rush-analyzer"
version = "0.1.1"
authors.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true
description = "A semantic analyzer and type-annotator for the rush programming language"

[dependencies]
rush-parser = "0.1.1"
