[package]
name = "rush-analyzer"
version = "0.1.0"
authors.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true

[dependencies]
rush-parser = { path = "../rush-parser/", version = "0.1.0" }
