[package]
name = "rush-compiler-x86-64"
version = "0.1.0"
authors.workspace = true
edition = "2021"
license.workspace = true
repository.workspace = true

[dependencies]
rush-analyzer = { path = "../rush-analyzer", version = "0.1.2" }
